apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: home-app
  template:
    metadata:
      labels:
        run: home-app
    spec:
      containers:
      - name: home-app
        image: gcr.io/leagueai/home-app:v1
        imagePullPolicy: Always
        env:
          - name: DB_URI
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_URI
      nodeSelector:
        component: web
